"""E2E test: full TRA pipeline on to_translate.md with a manual LLM hijack.

This is the canonical end-to-end regression test. It loads the real
`to_translate.md` source (a Chinese review of the TRA repo), hijacks the
`llm_translate` seam to return the pre-generated manual English translation
(`to_translate.en.md`), and runs the full Kernel pipeline at L3 and L4.

Assertions cover:
- Pipeline completes without ConformanceFailure at L3.
- Output matches the manual translation (the hijack works end-to-end).
- Audit trail has ≥6 records with the canonical ISA sequence
  (ANALYZE_DOCUMENT → BUILD_GLOSSARY → BUILD_ENTITY_TABLE →
  TRANSLATE_SEGMENT → VERIFY_OUTPUT → VERIFY_OUTPUT at L3+).
- Zero BLOCKING diagnostics at L3.
- All runtime artifacts are written (glossary, entity_table, structural_map,
  style_profile, execution_log, repair_history, audit_trace).
- L4 emits evidence_trace.jsonl + ambiguity_register.json (L4-only).
- Two runs produce byte-identical audit_trace.jsonl (TRA-013 reproducibility).

The manual translation (`to_translate.en.md`) is the "AI response" — it is
pre-generated by a human (or LLM-assisted) translator and returned by the
`llm_translate` callback. This simulates an AI-powered translation where
the TRA engine handles analysis, verification, repair, and audit while the
LLM provides the fluent phrasing.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from tra.config import BootstrapConfig
from tra.kernel import TRAKernel
from tra.memory import ConformanceLevel

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE_PATH = REPO_ROOT / "to_translate.md"
MANUAL_TRANSLATION_PATH = REPO_ROOT / "tra-prototype" / "to_translate.en.md"
CONFIG_PATH = REPO_ROOT / "tra-prototype" / "config.yaml"


def _load_source() -> str:
    """Load the Chinese source document."""
    return SOURCE_PATH.read_text(encoding="utf-8")


def _load_manual_translation() -> str:
    """Load the pre-generated manual English translation (the AI response)."""
    return MANUAL_TRANSLATION_PATH.read_text(encoding="utf-8")


def _make_cfg(tmp_path: Path, level: ConformanceLevel) -> BootstrapConfig:
    """Build a BootstrapConfig for the given conformance level, with all
    runtime artifacts isolated under tmp_path."""
    base = BootstrapConfig.from_yaml(str(CONFIG_PATH))
    return base.model_copy(
        update={
            "base_dir": str(tmp_path),
            "conformance_level": level,
            "audit_trace": str(tmp_path / "audit_trace.jsonl"),
            "compilation_dir": str(tmp_path / "compilation_artifacts"),
            "cache_directory": str(tmp_path / "cache"),
        }
    )


def _run_kernel_with_manual_llm(
    cfg: BootstrapConfig, source: str, manual_translation: str
) -> tuple[TRAKernel, str]:
    """Run the TRA kernel with the llm_translate seam hijacked to return
    the manual translation.

    Returns (kernel, target) so the caller can inspect the audit trail and
    artifacts.
    """
    call_count = 0

    def manual_llm(source_segment: str, ctx: object) -> str:
        nonlocal call_count
        call_count += 1
        return manual_translation

    # Patch translate_segment in the kernel's namespace so the kernel's
    # _execute_translation call picks up the llm_translate override.
    import tra.kernel as kernel_mod

    orig_translate = kernel_mod.translate_segment

    def patched_translate(source_segment, ctx, cache, evidence, audit, **kwargs):
        kwargs["llm_translate"] = manual_llm
        return orig_translate(source_segment, ctx, cache, evidence, audit, **kwargs)

    kernel_mod.translate_segment = patched_translate
    try:
        kernel = TRAKernel(cfg)
        target = kernel.run(source)
    finally:
        # Restore the original so other tests aren't affected.
        kernel_mod.translate_segment = orig_translate

    assert call_count >= 1, "llm_translate was never called — hijack failed"
    return kernel, target


# ---------------------------------------------------------------------------
# E2E tests
# ---------------------------------------------------------------------------


class TestE2EToTranslateL3:
    """E2E at L3_STRICT: the core happy-path regression."""

    def test_pipeline_completes_and_output_matches_manual_translation(
        self, tmp_path: Path
    ) -> None:
        """The full pipeline runs on to_translate.md at L3_STRICT, the
        llm_translate hijack returns the manual translation, and the
        kernel's output matches it byte-for-byte."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        kernel, target = _run_kernel_with_manual_llm(cfg, source, manual)

        # The hijack works: the kernel emits the manual translation verbatim.
        assert target == manual, (
            "kernel output does not match the manual translation — "
            "the llm_translate hijack failed"
        )

    def test_audit_trail_has_canonical_isa_sequence(self, tmp_path: Path) -> None:
        """The audit trail must contain the canonical ISA instruction
        sequence: ANALYZE_DOCUMENT → BUILD_GLOSSARY → BUILD_ENTITY_TABLE →
        TRANSLATE_SEGMENT → VERIFY_OUTPUT → VERIFY_OUTPUT (double at L3+)."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        records = kernel.audit._buffer
        isa_sequence = [r.isa_instruction for r in records]
        # Expected: 6 records at L3 (double VERIFY_OUTPUT from the L3 gate).
        expected = [
            "ANALYZE_DOCUMENT",
            "BUILD_GLOSSARY",
            "BUILD_ENTITY_TABLE",
            "TRANSLATE_SEGMENT",
            "VERIFY_OUTPUT",
            "VERIFY_OUTPUT",  # L3 gate's second verify
        ]
        assert isa_sequence == expected, (
            f"audit trail ISA sequence {isa_sequence} does not match "
            f"expected {expected}"
        )

    def test_zero_blocking_diagnostics_at_l3(self, tmp_path: Path) -> None:
        """At L3_STRICT, the pipeline must produce zero BLOCKING diagnostics
        — otherwise ConformanceFailure would be raised."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        # If this doesn't raise, zero BLOCKING (the L3 gate passed).
        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        # Double-check: count BLOCKING flags in the audit trail.
        blocking = sum(
            1
            for r in kernel.audit._buffer
            if r.flags_raised and "BLOCKING" in r.flags_raised
        )
        assert blocking == 0, f"expected 0 BLOCKING, got {blocking}"

    def test_all_runtime_artifacts_written_at_l3(self, tmp_path: Path) -> None:
        """All L3 runtime artifacts must be written to compilation_artifacts/."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        artifacts_dir = tmp_path / "compilation_artifacts"
        expected_files = [
            "glossary.yaml",
            "entity_table.yaml",
            "structural_map.json",
            "style_profile.yaml",
            "execution_log.json",
            "repair_history.jsonl",
        ]
        for fname in expected_files:
            assert (artifacts_dir / fname).exists(), (
                f"missing runtime artifact: {fname}"
            )

        # The audit_trace.jsonl must also be written (at the configured path).
        assert (tmp_path / "audit_trace.jsonl").exists()

    def test_glossary_contains_canonical_mappings(self, tmp_path: Path) -> None:
        """The exported glossary.yaml must contain the canonical ZH→EN
        mappings from the ZH-EN module (e.g. 成立 → Confirmed)."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        import yaml

        glossary_path = tmp_path / "compilation_artifacts" / "glossary.yaml"
        glossary = yaml.safe_load(glossary_path.read_text(encoding="utf-8"))
        assert glossary, "glossary.yaml is empty"
        # The ZH-EN module defines 成立 → Confirmed.
        sources = {entry["source"] for entry in glossary}
        assert "成立" in sources, (
            f"glossary missing canonical mapping for '成立'; sources={sources}"
        )

    def test_entity_table_preserves_entities(self, tmp_path: Path) -> None:
        """The exported entity_table.yaml must preserve entities found in
        the source (e.g. L1, L2, L3, L4, ISA, TRA)."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        import yaml

        entity_path = tmp_path / "compilation_artifacts" / "entity_table.yaml"
        entities = yaml.safe_load(entity_path.read_text(encoding="utf-8"))
        assert entities, "entity_table.yaml is empty"
        names = {e["name"] for e in entities}
        # The source contains L1, L2, L3, L4, ISA, TRA, etc.
        for expected_entity in ["L1", "L2", "L3", "L4", "ISA", "TRA"]:
            assert expected_entity in names, (
                f"entity {expected_entity!r} not preserved in entity_table; "
                f"names={names}"
            )

    def test_execution_log_matches_kernel_state_order(self, tmp_path: Path) -> None:
        """The exported execution_log.json must record the canonical Kernel
        state transitions (INITIALIZE_RUNTIME → ANALYZE_DOCUMENT → ... →
        EMIT_PAYLOAD)."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L3_STRICT)

        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        log_path = tmp_path / "compilation_artifacts" / "execution_log.json"
        log_data = json.loads(log_path.read_text(encoding="utf-8"))
        execution_log = log_data["execution_log"]
        # Expected state transitions (BOOTSTRAP is the initial state, not a
        # transition). The L3 gate adds a second VERIFY_OUTPUT audit record
        # but NOT a second state transition.
        expected = [
            "INITIALIZE_RUNTIME",
            "ANALYZE_DOCUMENT",
            "BUILD_ARTIFACTS",
            "EXECUTE_TRANSLATION",
            "VERIFY_OUTPUT",
            "REPAIR_IF_NEEDED",
            "AUDIT_DIAGNOSTICS",
            "EMIT_PAYLOAD",
        ]
        assert execution_log == expected, (
            f"execution_log {execution_log} does not match expected {expected}"
        )


class TestE2EToTranslateL4:
    """E2E at L4_FORENSIC: L4-specific artifacts and forensic tracing."""

    def test_l4_emits_forensic_artifacts(self, tmp_path: Path) -> None:
        """At L4_FORENSIC, the kernel must emit evidence_trace.jsonl and
        ambiguity_register.json in addition to the L3 artifacts."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L4_FORENSIC)

        kernel, _target = _run_kernel_with_manual_llm(cfg, source, manual)

        artifacts_dir = tmp_path / "compilation_artifacts"
        # L4-only artifacts.
        assert (artifacts_dir / "evidence_trace.jsonl").exists(), (
            "L4 must emit evidence_trace.jsonl"
        )
        assert (artifacts_dir / "ambiguity_register.json").exists(), (
            "L4 must emit ambiguity_register.json"
        )

    def test_evidence_trace_has_one_entry_per_output_line(self, tmp_path: Path) -> None:
        """The L4 evidence_trace.jsonl must have one entry per non-empty
        output line, each with an evidence_ids list (may be empty for
        unattributed lines)."""
        source = _load_source()
        manual = _load_manual_translation()
        cfg = _make_cfg(tmp_path, ConformanceLevel.L4_FORENSIC)

        kernel, target = _run_kernel_with_manual_llm(cfg, source, manual)

        trace_path = tmp_path / "compilation_artifacts" / "evidence_trace.jsonl"
        trace_lines = [
            json.loads(line)
            for line in trace_path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        # Each trace entry must have the required fields.
        for entry in trace_lines:
            assert "line" in entry, f"trace entry missing 'line': {entry}"
            assert "text" in entry, f"trace entry missing 'text': {entry}"
            assert "evidence_ids" in entry, (
                f"trace entry missing 'evidence_ids': {entry}"
            )
            assert "attributed" in entry, f"trace entry missing 'attributed': {entry}"
        # At least one entry must be attributed (have non-empty evidence_ids).
        attributed = [e for e in trace_lines if e["evidence_ids"]]
        assert attributed, "no trace entries are attributed — evidence_trace is empty"


class TestE2EToTranslateReproducibility:
    """TRA-013: two runs of identical source produce byte-identical artifacts."""

    def test_two_runs_produce_byte_identical_audit_trace(self, tmp_path: Path) -> None:
        """Two runs of the same source at L4 must produce byte-identical
        audit_trace.jsonl (TRA-013 deterministic clock + content-addressed
        evidence IDs)."""
        source = _load_source()
        manual = _load_manual_translation()

        # Run 1
        cfg1 = _make_cfg(tmp_path / "run1", ConformanceLevel.L4_FORENSIC)
        kernel1, _t1 = _run_kernel_with_manual_llm(cfg1, source, manual)
        audit1 = (tmp_path / "run1" / "audit_trace.jsonl").read_bytes()

        # Run 2 (clean cache)
        cfg2 = _make_cfg(tmp_path / "run2", ConformanceLevel.L4_FORENSIC)
        kernel2, _t2 = _run_kernel_with_manual_llm(cfg2, source, manual)
        audit2 = (tmp_path / "run2" / "audit_trace.jsonl").read_bytes()

        sha1 = hashlib.sha256(audit1).hexdigest()
        sha2 = hashlib.sha256(audit2).hexdigest()
        assert sha1 == sha2, (
            f"audit_trace.jsonl not byte-identical across runs (TRA-013): "
            f"run1={sha1[:16]} run2={sha2[:16]}"
        )

    def test_two_runs_produce_byte_identical_evidence_trace(
        self, tmp_path: Path
    ) -> None:
        """Two runs of the same source at L4 must produce byte-identical
        evidence_trace.jsonl (L4 forensic hash-chain integrity)."""
        source = _load_source()
        manual = _load_manual_translation()

        cfg1 = _make_cfg(tmp_path / "run1", ConformanceLevel.L4_FORENSIC)
        _run_kernel_with_manual_llm(cfg1, source, manual)
        trace1 = (
            tmp_path / "run1" / "compilation_artifacts" / "evidence_trace.jsonl"
        ).read_bytes()

        cfg2 = _make_cfg(tmp_path / "run2", ConformanceLevel.L4_FORENSIC)
        _run_kernel_with_manual_llm(cfg2, source, manual)
        trace2 = (
            tmp_path / "run2" / "compilation_artifacts" / "evidence_trace.jsonl"
        ).read_bytes()

        sha1 = hashlib.sha256(trace1).hexdigest()
        sha2 = hashlib.sha256(trace2).hexdigest()
        assert sha1 == sha2, (
            f"evidence_trace.jsonl not byte-identical across runs: "
            f"run1={sha1[:16]} run2={sha2[:16]}"
        )

    def test_two_runs_produce_byte_identical_output(self, tmp_path: Path) -> None:
        """Two runs of the same source must produce byte-identical output .md."""
        source = _load_source()
        manual = _load_manual_translation()

        cfg1 = _make_cfg(tmp_path / "run1", ConformanceLevel.L4_FORENSIC)
        _k1, t1 = _run_kernel_with_manual_llm(cfg1, source, manual)

        cfg2 = _make_cfg(tmp_path / "run2", ConformanceLevel.L4_FORENSIC)
        _k2, t2 = _run_kernel_with_manual_llm(cfg2, source, manual)

        assert t1 == t2, "output not byte-identical across runs"
